FROM node:18-slim AS builder

WORKDIR /app
COPY mars-ui/package*.json ./
RUN npm ci
COPY mars-ui/ ./
RUN npm run build

FROM node:18-slim

WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["./node_modules/.bin/next", "start"]